name: flutter_application_1
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter_bloc: ^8.0.0
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  bloc: ^8.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/wallapers.jpg

fonts:
  - family: Roboto
    fonts:
      - assets: fonts/Roboto-Black.ttf
